In [1]:
import pandas as pd
import re
from nltk.tokenize import RegexpTokenizer

# print non truncated column info in pandas dataframe
pd.set_option('display.max_colwidth', -1)
pd.set_option('display.max_columns', 500)

In [2]:
# from main import *

# df_list = []
# for category in categories[0:]:
#     dir_ = '/home/ubuntu/Spitishop/diss/results/'+category['Category']+'-'+category['SubCategory']+'.csv'
#     #print(dir_)
#     df = pd.read_csv(dir_)
#     df_list.append(df)
    
# df = pd.concat(df_list, axis=0)

# df.to_pickle('data/df_init.pkl')

In [3]:
df = pd.read_pickle('data/product_details/df_init.pkl')

In [4]:
df.head(2)

,Category,SubCategory,url,N,Title,Price,Popularity,Description,Page,brand_name,brand_url
0,Mobiles,Mobile_phone,https://www.bestprice.gr/item/2155531584/samsung-galaxy-s10-128gb-dual.html,1600,Samsung Galaxy S10+ 128GB Dual,595.00€,26,"Οθόνη: 6.4"", Android 9, RAM: 8GB, Μνήμη: 128GB, Κάμερα: 12MP + 12MP + 16MP, Selfie: 10MP + 8MP, CPU: Οκταπύρηνος (2+2+4)",2,Samsung,https://www.bestprice.gr/cat/806/mobile-phones/f/1_26/samsung.html&pg={}
1,Mobiles,Mobile_phone,https://www.bestprice.gr/item/2155621215/samsung-galaxy-a70-6gb-128gb-dual.html,1600,Samsung Galaxy A70 6GB 128GB Dual,279.00€,28,"Οθόνη: 6.7"", Android 9, RAM: 6GB, Μνήμη: 128GB, Κάμερα: 32MP + 8MP + 5MP, Selfie: 32MP, CPU: Οκταπύρηνος (6+2)",2,Samsung,https://www.bestprice.gr/cat/806/mobile-phones/f/1_26/samsung.html&pg={}

In [11]:
df[['Category', 'SubCategory', 'brand_name', 'Title']].head(5)

  Category   SubCategory brand_name                                    Title
0  Mobiles  Mobile_phone  Samsung    Samsung Galaxy S10+ 128GB Dual
1  Mobiles  Mobile_phone  Samsung    Samsung Galaxy A70 6GB 128GB Dual
2  Mobiles  Mobile_phone  Samsung    Samsung Galaxy Note 10+ 12GB 256GB Dual
3  Mobiles  Mobile_phone  Samsung    Samsung Galaxy S10 128GB Dual
4  Mobiles  Mobile_phone  Samsung    Samsung Galaxy S10e 128GB Dual

In [5]:
df.columns

Index(['Category', 'SubCategory', 'url', 'N', 'Title', 'Price', 'Popularity',
       'Description', 'Page', 'brand_name', 'brand_url'],
      dtype='object')

In [6]:
print('Number of rows:', len(df))

Number of rows: 32324

In [7]:
print('Number of unique products: ', df.url.nunique())

Number of unique products:  29541

In [9]:
print('Number of unique brands: ', df.brand_name.nunique())

Number of unique brands:  515

In [8]:
df.groupby(['Category', 'SubCategory'], as_index=False).agg({#'SubCategory':'nunique', 
                                              'url':'nunique', 
                                              'brand_name':'nunique'})

         Category         SubCategory   url  brand_name
0   Desktop_pc     Desktop             709   7
1   Desktop_pc     Desktop_monitors    1998  25
2   Desktop_pc     Desktop_rams        2507  25
3   Laptop_pc      Laptop              2718  19
4   Laptop_pc      Laptop_bases        172   19
5   Laptop_pc      Laptop_battery      6160  23
6   Laptop_pc      Laptop_cases        1678  92
7   Mobiles        Bluetooth           609   47
8   Mobiles        Handsfree           943   77
9   Mobiles        Mobile_phone        879   60
10  Mobiles        Portable_speaker    2117  135
11  Mobiles        Power_bank          1530  74
12  Photograph     Analog              34    4
13  Photograph     Compact             133   9
14  Photograph     DSLR                160   3
15  Photograph     Photograph_battery  1556  23
16  Photograph     Photograph_cases    1925  49
17  Tablets_other  Tablet_bases        173   19
18  Tablets_other  Tablet_cases        2368  93
19  Tablets_other  Tablet_chargers     180   11
20  Tablets_other  Tablets             534   27
21  Wearables      Smartwatch          413   21
22  Wearables      Transmitter         45    3

In [9]:
df_dubl = df.groupby(['url'], as_index=False).agg({'brand_name':'count'})
df_dubl = df_dubl.sort_values(by=['brand_name'], ascending=False)
df_dubl.head(2)

,url,brand_name
26565,https://www.bestprice.gr/item/39439256/symbath-bataria-asus-eee-pc-74v-4600mah-kwdikos-antistoixias-lcb343.html?seq=1391,7
26566,https://www.bestprice.gr/item/39439258/symbath-bataria-asus-eee-pc-74v-4600mah-kwdikos-antistoixias-a22-p701.html?seq=1390,7

In [10]:
df_dubl.loc[0][0]

'https://www.bestprice.gr/item/10338201/sony-case-lcs-u11.html?seq=19'

In [11]:
df[df.url=='https://www.bestprice.gr/item/39439256/symbath-bataria-asus-eee-pc-74v-4600mah-kwdikos-antistoixias-lcb343.html?seq=1391']

,Category,SubCategory,url,N,Title,Price,Popularity,Description,Page,brand_name,brand_url
1381,Laptop_pc,Laptop_battery,https://www.bestprice.gr/item/39439256/symbath-bataria-asus-eee-pc-74v-4600mah-kwdikos-antistoixias-lcb343.html?seq=1391,9200,Συμβατή Μπαταρία Asus Eee PC (White) 7.4V 4600mAh Κωδικός αντιστοιχίας: LCB343,29.99€,1244,NaN,50,2-Power,https://www.bestprice.gr/cat/2596/mpataries-laptop/f/1_1520/2-power.html?v=r&pg={}
1437,Laptop_pc,Laptop_battery,https://www.bestprice.gr/item/39439256/symbath-bataria-asus-eee-pc-74v-4600mah-kwdikos-antistoixias-lcb343.html?seq=1391,9200,Συμβατή Μπαταρία Asus Eee PC (White) 7.4V 4600mAh Κωδικός αντιστοιχίας: LCB343,29.99€,1294,NaN,52,2-Power,https://www.bestprice.gr/cat/2596/mpataries-laptop/f/1_1520/2-power.html?v=r&pg={}
1465,Laptop_pc,Laptop_battery,https://www.bestprice.gr/item/39439256/symbath-bataria-asus-eee-pc-74v-4600mah-kwdikos-antistoixias-lcb343.html?seq=1391,9200,Συμβατή Μπαταρία Asus Eee PC (White) 7.4V 4600mAh Κωδικός αντιστοιχίας: LCB343,29.99€,1319,NaN,53,2-Power,https://www.bestprice.gr/cat/2596/mpataries-laptop/f/1_1520/2-power.html?v=r&pg={}
1493,Laptop_pc,Laptop_battery,https://www.bestprice.gr/item/39439256/symbath-bataria-asus-eee-pc-74v-4600mah-kwdikos-antistoixias-lcb343.html?seq=1391,9200,Συμβατή Μπαταρία Asus Eee PC (White) 7.4V 4600mAh Κωδικός αντιστοιχίας: LCB343,29.99€,1344,NaN,54,2-Power,https://www.bestprice.gr/cat/2596/mpataries-laptop/f/1_1520/2-power.html?v=r&pg={}
1521,Laptop_pc,Laptop_battery,https://www.bestprice.gr/item/39439256/symbath-bataria-asus-eee-pc-74v-4600mah-kwdikos-antistoixias-lcb343.html?seq=1391,9200,Συμβατή Μπαταρία Asus Eee PC (White) 7.4V 4600mAh Κωδικός αντιστοιχίας: LCB343,29.99€,1369,NaN,55,2-Power,https://www.bestprice.gr/cat/2596/mpataries-laptop/f/1_1520/2-power.html?v=r&pg={}
1549,Laptop_pc,Laptop_battery,https://www.bestprice.gr/item/39439256/symbath-bataria-asus-eee-pc-74v-4600mah-kwdikos-antistoixias-lcb343.html?seq=1391,9200,Συμβατή Μπαταρία Asus Eee PC (White) 7.4V 4600mAh Κωδικός αντιστοιχίας: LCB343,29.99€,1394,NaN,56,2-Power,https://www.bestprice.gr/cat/2596/mpataries-laptop/f/1_1520/2-power.html?v=r&pg={}
1577,Laptop_pc,Laptop_battery,https://www.bestprice.gr/item/39439256/symbath-bataria-asus-eee-pc-74v-4600mah-kwdikos-antistoixias-lcb343.html?seq=1391,9200,Συμβατή Μπαταρία Asus Eee PC (White) 7.4V 4600mAh Κωδικός αντιστοιχίας: LCB343,29.99€,1419,NaN,57,2-Power,https://www.bestprice.gr/cat/2596/mpataries-laptop/f/1_1520/2-power.html?v=r&pg={}

## - Preprocess

### -- Create unique ID

Extract the id number from each product url

In [12]:
df['product_id'] = df['url'].apply(lambda x: re.search(r"item\/([^']*)\/", x).group(1))

In [13]:
df.head(1)

,Category,SubCategory,url,N,Title,Price,Popularity,Description,Page,brand_name,brand_url,product_id
0,Mobiles,Mobile_phone,https://www.bestprice.gr/item/2155531584/samsung-galaxy-s10-128gb-dual.html,1600,Samsung Galaxy S10+ 128GB Dual,595.00€,26,"Οθόνη: 6.4"", Android 9, RAM: 8GB, Μνήμη: 128GB, Κάμερα: 12MP + 12MP + 16MP, Selfie: 10MP + 8MP, CPU: Οκταπύρηνος (2+2+4)",2,Samsung,https://www.bestprice.gr/cat/806/mobile-phones/f/1_26/samsung.html&pg={},2155531584

In [14]:
df.product_id.nunique()

29541

### -- Lowercase

In [15]:
# convert category to lowercase
df['Category_lc'] = df['Category'].apply(lambda text: text.lower())
# convert SubCategory to lowercase
df['SubCategory_lc'] = df['SubCategory'].apply(lambda text: text.lower())
# convert brand_name to lowercase
df['brand_name_lc'] = df['brand_name'].apply(lambda text: text.lower())
# convert category to lowercase
df['Title_lc'] = df['Title'].apply(lambda text: text.lower())

### -- Convert Category, SubCategory & brand_name

In [16]:
# add the string '_cat' after the category
df['Category2'] = df['Category_lc'].apply(lambda x: x+'_cat')

In [17]:
# add the string '_subcat' after the SubCategory
df['SubCategory2'] = df['SubCategory_lc'].apply(lambda x: x+'_subcat')

In [18]:
# add the string '_brand' after the brand_name
df['brand_name2'] = df['brand_name_lc'].apply(lambda x: x+'_brand')

### -- Replace brands

In each product title, replace the brand name with the 'brand_name2' column. If the brand name is not present in the title, then just add the 'brand_name2' column

In [32]:
def replace_brand(row):
    title = row['Title_lc']
    brand = row['brand_name_lc']
    brand2 = row['brand_name2']
    
    if brand in title:
        title2 = re.sub(brand, brand2, title)
    else:
        title2 = title +' '+ brand2
        
    return title2

In [33]:
df['Title_lc2'] = df[['Title_lc', 'brand_name_lc', 'brand_name2']].apply(lambda x: replace_brand(x), axis=1)

In [40]:
df.head(1)

,Category,SubCategory,url,N,Title,Price,Popularity,Description,Page,brand_name,brand_url,product_id,Category_lc,SubCategory_lc,brand_name_lc,Title_lc,Category2,SubCategory2,brand_name2,Title_lc2
0,Mobiles,Mobile_phone,https://www.bestprice.gr/item/2155531584/samsung-galaxy-s10-128gb-dual.html,1600,Samsung Galaxy S10+ 128GB Dual,595.00€,26,"Οθόνη: 6.4"", Android 9, RAM: 8GB, Μνήμη: 128GB, Κάμερα: 12MP + 12MP + 16MP, Selfie: 10MP + 8MP, CPU: Οκταπύρηνος (2+2+4)",2,Samsung,https://www.bestprice.gr/cat/806/mobile-phones/f/1_26/samsung.html&pg={},2155531584,mobiles,mobile_phone,samsung,samsung galaxy s10+ 128gb dual,mobiles_cat,mobile_phone_subcat,samsung_brand,samsung_brand galaxy s10+ 128gb dual mobiles_cat mobile_phone_subcat

### -- Add category & sub-category

In [37]:
# add category in the end of the product title
df['Title_lc2'] = df[['Title_lc2', 'Category2']].apply(lambda x: x['Title_lc2']+' '+x['Category2'], axis=1)

In [39]:
# add sub-category in the end of the product title
df['Title_lc2'] = df[['Title_lc2', 'SubCategory2']].apply(lambda x: x['Title_lc2']+' '+x['SubCategory2'], axis=1)

### -- Finalize and save the dataframe

In [44]:
# keep only useful columns
df = df[['product_id', 'url', 'Title', 'Category2', 'SubCategory2', 'brand_name2', 'Title_lc2']]

In [51]:
# keep only unique products
df = df.drop_duplicates(subset='product_id', keep='first')

In [52]:
df.head(2)

,product_id,url,Title,Category2,SubCategory2,brand_name2,Title_lc2
0,2155531584,https://www.bestprice.gr/item/2155531584/samsung-galaxy-s10-128gb-dual.html,Samsung Galaxy S10+ 128GB Dual,mobiles_cat,mobile_phone_subcat,samsung_brand,samsung_brand galaxy s10+ 128gb dual mobiles_cat mobile_phone_subcat
1,2155621215,https://www.bestprice.gr/item/2155621215/samsung-galaxy-a70-6gb-128gb-dual.html,Samsung Galaxy A70 6GB 128GB Dual,mobiles_cat,mobile_phone_subcat,samsung_brand,samsung_brand galaxy a70 6gb 128gb dual mobiles_cat mobile_phone_subcat

In [53]:
df.shape

(29541, 7)

In [56]:
df.Title_lc2.nunique()

28293

In [57]:
# save the dataframe as pickle file
df.to_pickle('data/product_details/df_preproc.pkl')

In [12]:
dff = pd.read_pickle('data/product_details/df_preproc.pkl')

In [40]:
dff[dff.SubCategory2=='smartwatch_subcat'].brand_name2.unique()

array(['apple_brand', 'samsung_brand', 'huawei_brand',
       'michael kors_brand', 'fossil_brand', 'media-tech_brand',
       'mykronoz_brand', 'brigmton_brand', 'lemfo_brand', 'xlyne_brand',
       'guess_brand', 'diesel_brand', 'forever_brand', 'overmax_brand',
       'armani exchange_brand', 'emporio armani_brand', 'elari_brand',
       'skagen_brand', 'kronaby_brand', 'armani_brand', 'ticwatch_brand'],
      dtype=object)

In [42]:
dff[(dff.SubCategory2=='smartwatch_subcat')&(dff.brand_name2=='huawei_brand')]

,product_id,url,Title,Category2,SubCategory2,brand_name2,Title_lc2
131,2155432313,https://www.bestprice.gr/item/2155432313/huawei-watch-gt-graphite-black.html,Huawei Watch GT Graphite Black,wearables_cat,smartwatch_subcat,huawei_brand,huawei_brand watch gt graphite black wearables_cat smartwatch_subcat
132,2155568892,https://www.bestprice.gr/item/2155568892/huawei-watch-gt-active-dark-green.html,Huawei Watch GT Active Dark Green,wearables_cat,smartwatch_subcat,huawei_brand,huawei_brand watch gt active dark green wearables_cat smartwatch_subcat
133,2155011191,https://www.bestprice.gr/item/2155011191/huawei-watch-2-carbon-black.html,Huawei Watch 2 Carbon Black,wearables_cat,smartwatch_subcat,huawei_brand,huawei_brand watch 2 carbon black wearables_cat smartwatch_subcat
134,2155615133,https://www.bestprice.gr/item/2155615133/huawei-watch-gt-elegant-version-black.html,Huawei Watch GT Elegant Version Black,wearables_cat,smartwatch_subcat,huawei_brand,huawei_brand watch gt elegant version black wearables_cat smartwatch_subcat
135,2155633716,https://www.bestprice.gr/item/2155633716/huawei-watch-gt-elegant-white.html,Huawei Watch GT Elegant White,wearables_cat,smartwatch_subcat,huawei_brand,huawei_brand watch gt elegant white wearables_cat smartwatch_subcat
136,2155432315,https://www.bestprice.gr/item/2155432315/huawei-watch-gt-saddle-brown.html,Huawei Watch GT Saddle Brown,wearables_cat,smartwatch_subcat,huawei_brand,huawei_brand watch gt saddle brown wearables_cat smartwatch_subcat
137,2155568893,https://www.bestprice.gr/item/2155568893/huawei-watch-gt-active-dark-orange.html,Huawei Watch GT Active Dark Orange,wearables_cat,smartwatch_subcat,huawei_brand,huawei_brand watch gt active dark orange wearables_cat smartwatch_subcat
138,2155431811,https://www.bestprice.gr/item/2155431811/huawei-watch-2-classic-titanium-grey.html,Huawei Watch 2 Classic Titanium Grey,wearables_cat,smartwatch_subcat,huawei_brand,huawei_brand watch 2 classic titanium grey wearables_cat smartwatch_subcat
139,2155011192,https://www.bestprice.gr/item/2155011192/huawei-watch-2-lte-carbon-black.html,Huawei Watch 2 LTE Carbon Black,wearables_cat,smartwatch_subcat,huawei_brand,huawei_brand watch 2 lte carbon black wearables_cat smartwatch_subcat

In [38]:
dff[25400:25410]

,product_id,url,Title,Category2,SubCategory2,brand_name2,Title_lc2
145,2155431797,https://www.bestprice.gr/item/2155431797/michael-kors-grayson-mens-mkt5026.html,Michael Kors Grayson Mens MKT5026,wearables_cat,smartwatch_subcat,michael kors_brand,michael kors_brand grayson mens mkt5026 wearables_cat smartwatch_subcat
146,2155248548,https://www.bestprice.gr/item/2155248548/michael-kors-bradshaw-mkt5001.html,Michael Kors Bradshaw MKT5001,wearables_cat,smartwatch_subcat,michael kors_brand,michael kors_brand bradshaw mkt5001 wearables_cat smartwatch_subcat
147,2155689008,https://www.bestprice.gr/item/2155689008/michael-kors-mens-mkt4000.html,Michael Kors Mens MKT4000,wearables_cat,smartwatch_subcat,michael kors_brand,michael kors_brand mens mkt4000 wearables_cat smartwatch_subcat
148,2155718293,https://www.bestprice.gr/item/2155718293/michael-kors-access-sofie-crystals-pink.html,Michael Kors Access Sofie Crystals Pink,wearables_cat,smartwatch_subcat,michael kors_brand,michael kors_brand access sofie crystals pink wearables_cat smartwatch_subcat
149,2155718295,https://www.bestprice.gr/item/2155718295/michael-kors-access-runway-black.html,Michael Kors Access Runway Black,wearables_cat,smartwatch_subcat,michael kors_brand,michael kors_brand access runway black wearables_cat smartwatch_subcat
150,2155689012,https://www.bestprice.gr/item/2155689012/michael-kors-unisex-mkt5037.html,Michael Kors Unisex MKT5037,wearables_cat,smartwatch_subcat,michael kors_brand,michael kors_brand unisex mkt5037 wearables_cat smartwatch_subcat
151,2155689002,https://www.bestprice.gr/item/2155689002/michael-kors-unisex-mkt4025.html,Michael Kors Unisex MKT4025,wearables_cat,smartwatch_subcat,michael kors_brand,michael kors_brand unisex mkt4025 wearables_cat smartwatch_subcat
152,2155678181,https://www.bestprice.gr/item/2155678181/michael-kors-access-mens-reid-black.html,Michael Kors Access Mens Reid Black,wearables_cat,smartwatch_subcat,michael kors_brand,michael kors_brand access mens reid black wearables_cat smartwatch_subcat
153,2155595003,https://www.bestprice.gr/item/2155595003/michael-kors-access-runway-black.html,Michael Kors Access Runway Black,wearables_cat,smartwatch_subcat,michael kors_brand,michael kors_brand access runway black wearables_cat smartwatch_subcat
154,2155587299,https://www.bestprice.gr/item/2155587299/michael-kors-mkt5053-black-gold.html,Michael Kors MKT5053 Black / Gold,wearables_cat,smartwatch_subcat,michael kors_brand,michael kors_brand mkt5053 black / gold wearables_cat smartwatch_subcat

In [44]:
ids = ['2155531584', '2155112026', '2154004522', '2155081727', '2155432313']
dff[dff.product_id.isin(ids)]

,product_id,url,Title,Category2,SubCategory2,brand_name2,Title_lc2
0,2155531584,https://www.bestprice.gr/item/2155531584/samsung-galaxy-s10-128gb-dual.html,Samsung Galaxy S10+ 128GB Dual,mobiles_cat,mobile_phone_subcat,samsung_brand,samsung_brand galaxy s10+ 128gb dual mobiles_cat mobile_phone_subcat
369,2155112026,https://www.bestprice.gr/item/2155112026/sony-sbh56.html,Sony SBH56,mobiles_cat,bluetooth_subcat,sony_brand,sony_brand sbh56 mobiles_cat bluetooth_subcat
29,2154004522,https://www.bestprice.gr/item/2154004522/omega-ice-box.html,Omega Ice Box,laptop_pc_cat,laptop_bases_subcat,omega_brand,omega_brand ice box laptop_pc_cat laptop_bases_subcat
1587,2155081727,https://www.bestprice.gr/item/2155081727/lenovo-thinkvision-t24i.html,Lenovo Thinkvision T24I,desktop_pc_cat,desktop_monitors_subcat,lenovo_brand,lenovo_brand thinkvision t24i desktop_pc_cat desktop_monitors_subcat
131,2155432313,https://www.bestprice.gr/item/2155432313/huawei-watch-gt-graphite-black.html,Huawei Watch GT Graphite Black,wearables_cat,smartwatch_subcat,huawei_brand,huawei_brand watch gt graphite black wearables_cat smartwatch_subcat